// Achievements Seed - 50+ Achievements in 5 Kategorien
// LEARNING, EXPLORATION, COLLECTION, SOCIAL, MASTER

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedAchievements() {
  console.log('Starting Achievements Seed - 50+ Achievements...');

  const achievements = [
    // ========== CATEGORY: LEARNING (15 Achievements) ==========
    {
      key: 'first_lesson',
      name: 'Erste Schritte',
      description: 'Schließe deine erste Lektion ab.',
      category: 'LEARNING',
      icon: '📖',
      requirement: 1,
      rewardXp: 50,
      isSecret: false,
    },
    {
      key: 'lessons_10',
      name: 'Wissbegieriger',
      description: 'Schließe 10 Lektionen ab.',
      category: 'LEARNING',
      icon: '📚',
      requirement: 10,
      rewardXp: 100,
      isSecret: false,
    },
    {
      key: 'lessons_25',
      name: 'Gelehrter',
      description: 'Schließe 25 Lektionen ab.',
      category: 'LEARNING',
      icon: '🎓',
      requirement: 25,
      rewardXp: 250,
      isSecret: false,
    },
    {
      key: 'lessons_50',
      name: 'Schriftgelehrter',
      description: 'Schließe 50 Lektionen ab.',
      category: 'LEARNING',
      icon: '📜',
      requirement: 50,
      rewardXp: 500,
      isSecret: false,
    },
    {
      key: 'lessons_100',
      name: 'Meister der Schrift',
      description: 'Schließe 100 Lektionen ab.',
      category: 'LEARNING',
      icon: '👨‍🏫',
      requirement: 100,
      rewardXp: 1000,
      isSecret: false,
    },
    {
      key: 'perfect_lesson',
      name: 'Perfektionist',
      description: 'Beantworte alle Fragen einer Lektion richtig.',
      category: 'LEARNING',
      icon: '💯',
      requirement: 1,
      rewardXp: 100,
      isSecret: false,
    },
    {
      key: 'perfect_10',
      name: 'Fehlerlos',
      description: 'Schließe 10 Lektionen perfekt ab.',
      category: 'LEARNING',
      icon: '⭐',
      requirement: 10,
      rewardXp: 500,
      isSecret: false,
    },
    {
      key: 'level_5',
      name: 'Jünger',
      description: 'Erreiche Level 5.',
      category: 'LEARNING',
      icon: '🌱',
      requirement: 5,
      rewardXp: 200,
      isSecret: false,
    },
    {
      key: 'level_10',
      name: 'Diener',
      description: 'Erreiche Level 10.',
      category: 'LEARNING',
      icon: '🌿',
      requirement: 10,
      rewardXp: 500,
      isSecret: false,
    },
    {
      key: 'level_20',
      name: 'Lehrer',
      description: 'Erreiche Level 20.',
      category: 'LEARNING',
      icon: '🌳',
      requirement: 20,
      rewardXp: 1000,
      isSecret: false,
    },
    {
      key: 'level_50',
      name: 'Apostel',
      description: 'Erreiche Level 50.',
      category: 'LEARNING',
      icon: '👑',
      requirement: 50,
      rewardXp: 5000,
      isSecret: false,
    },
    {
      key: 'ot_master',
      name: 'AT Meister',
      description: 'Schließe 30 Lektionen aus dem Alten Testament ab.',
      category: 'LEARNING',
      icon: '📿',
      requirement: 30,
      rewardXp: 750,
      isSecret: false,
    },
    {
      key: 'nt_master',
      name: 'NT Meister',
      description: 'Schließe 30 Lektionen aus dem Neuen Testament ab.',
      category: 'LEARNING',
      icon: '✝️',
      requirement: 30,
      rewardXp: 750,
      isSecret: false,
    },
    {
      key: 'gospels_complete',
      name: 'Evangelien-Kenner',
      description: 'Schließe alle Lektionen aus den 4 Evangelien ab.',
      category: 'LEARNING',
      icon: '📕',
      requirement: 20,
      rewardXp: 1000,
      isSecret: false,
    },
    {
      key: 'paul_expert',
      name: 'Paulus-Experte',
      description: 'Schließe alle Lektionen aus den Paulus-Briefen ab.',
      category: 'LEARNING',
      icon: '✉️',
      requirement: 30,
      rewardXp: 1000,
      isSecret: false,
    },

    // ========== CATEGORY: EXPLORATION (15 Achievements) ==========
    {
      key: 'first_mission',
      name: 'Abenteurer',
      description: 'Schließe deine erste Mission ab.',
      category: 'EXPLORATION',
      icon: '🗺️',
      requirement: 1,
      rewardXp: 75,
      isSecret: false,
    },
    {
      key: 'missions_5',
      name: 'Entdecker',
      description: 'Schließe 5 Missionen ab.',
      category: 'EXPLORATION',
      icon: '🧭',
      requirement: 5,
      rewardXp: 250,
      isSecret: false,
    },
    {
      key: 'missions_10',
      name: 'Missionar',
      description: 'Schließe 10 Missionen ab.',
      category: 'EXPLORATION',
      icon: '🌍',
      requirement: 10,
      rewardXp: 500,
      isSecret: false,
    },
    {
      key: 'missions_all',
      name: 'Weltreisender',
      description: 'Schließe alle verfügbaren Missionen ab.',
      category: 'EXPLORATION',
      icon: '🌏',
      requirement: 15,
      rewardXp: 1500,
      isSecret: false,
    },
    {
      key: 'boss_battle_1',
      name: 'Kämpfer',
      description: 'Gewinne deinen ersten Boss-Battle.',
      category: 'EXPLORATION',
      icon: '⚔️',
      requirement: 1,
      rewardXp: 150,
      isSecret: false,
    },
    {
      key: 'boss_battle_all',
      name: 'Boss-Bezwinger',
      description: 'Gewinne alle Boss-Battles.',
      category: 'EXPLORATION',
      icon: '🛡️',
      requirement: 5,
      rewardXp: 1000,
      isSecret: false,
    },
    {
      key: 'exodus_arc',
      name: 'Befreier',
      description: 'Schließe alle Exodus-Missionen ab.',
      category: 'EXPLORATION',
      icon: '🌊',
      requirement: 3,
      rewardXp: 500,
      isSecret: false,
    },
    {
      key: 'jesus_arc',
      name: 'Nachfolger',
      description: 'Schließe alle Jesus-Missionen ab.',
      category: 'EXPLORATION',
      icon: '✝️',
      requirement: 3,
      rewardXp: 500,
      isSecret: false,
    },
    {
      key: 'apostles_arc',
      name: 'Apostel-Begleiter',
      description: 'Schließe alle Apostelgeschichte-Missionen ab.',
      category: 'EXPLORATION',
      icon: '🕊️',
      requirement: 2,
      rewardXp: 400,
      isSecret: false,
    },
    {
      key: 'speed_runner',
      name: 'Schnellläufer',
      description: 'Schließe eine Mission in Rekordzeit ab.',
      category: 'EXPLORATION',
      icon: '⚡',
      requirement: 1,
      rewardXp: 200,
      isSecret: false,
    },
    {
      key: 'no_damage',
      name: 'Unbezwingbar',
      description: 'Schließe eine Mission ohne Fehler ab.',
      category: 'EXPLORATION',
      icon: '🛡️',
      requirement: 1,
      rewardXp: 300,
      isSecret: false,
    },
    {
      key: 'resources_1000',
      name: 'Sammler',
      description: 'Sammle 1000 Ressourcen in Missionen.',
      category: 'EXPLORATION',
      icon: '💎',
      requirement: 1000,
      rewardXp: 400,
      isSecret: false,
    },
    {
      key: 'all_objectives',
      name: 'Vollender',
      description: 'Schließe alle Objectives einer Mission ab.',
      category: 'EXPLORATION',
      icon: '✅',
      requirement: 1,
      rewardXp: 150,
      isSecret: false,
    },
    {
      key: 'mission_streak_3',
      name: 'Mission Marathoner',
      description: 'Schließe 3 Missionen an aufeinanderfolgenden Tagen ab.',
      category: 'EXPLORATION',
      icon: '🏃',
      requirement: 3,
      rewardXp: 300,
      isSecret: false,
    },
    {
      key: 'all_types',
      name: 'Vielseitig',
      description: 'Schließe jeden Missions-Typ mindestens einmal ab.',
      category: 'EXPLORATION',
      icon: '🎯',
      requirement: 5,
      rewardXp: 500,
      isSecret: false,
    },

    // ========== CATEGORY: COLLECTION (12 Achievements) ==========
    {
      key: 'first_fragment',
      name: 'Erste Entdeckung',
      description: 'Schalte dein erstes Fragment frei.',
      category: 'COLLECTION',
      icon: '🔓',
      requirement: 1,
      rewardXp: 50,
      isSecret: false,
    },
    {
      key: 'fragments_10',
      name: 'Sammler',
      description: 'Schalte 10 Fragmente frei.',
      category: 'COLLECTION',
      icon: '📖',
      requirement: 10,
      rewardXp: 200,
      isSecret: false,
    },
    {
      key: 'fragments_25',
      name: 'Archivar',
      description: 'Schalte 25 Fragmente frei.',
      category: 'COLLECTION',
      icon: '📚',
      requirement: 25,
      rewardXp: 500,
      isSecret: false,
    },
    {
      key: 'fragments_50',
      name: 'Historiker',
      description: 'Schalte 50 Fragmente frei.',
      category: 'COLLECTION',
      icon: '🏛️',
      requirement: 50,
      rewardXp: 1000,
      isSecret: false,
    },
    {
      key: 'fragments_all',
      name: 'Meister-Sammler',
      description: 'Schalte alle Fragmente frei. 100% Completion!',
      category: 'COLLECTION',
      icon: '👑',
      requirement: 60,
      rewardXp: 5000,
      isSecret: false,
    },
    {
      key: 'all_characters',
      name: 'Charakterkenner',
      description: 'Sammle alle Charakter-Fragmente.',
      category: 'COLLECTION',
      icon: '👥',
      requirement: 20,
      rewardXp: 1000,
      isSecret: false,
    },
    {
      key: 'all_locations',
      name: 'Weltenbummler',
      description: 'Sammle alle Orts-Fragmente.',
      category: 'COLLECTION',
      icon: '🗺️',
      requirement: 15,
      rewardXp: 750,
      isSecret: false,
    },
    {
      key: 'all_concepts',
      name: 'Theologe',
      description: 'Sammle alle Konzept-Fragmente.',
      category: 'COLLECTION',
      icon: '🧠',
      requirement: 15,
      rewardXp: 750,
      isSecret: false,
    },
    {
      key: 'first_equipment',
      name: 'Ausgerüstet',
      description: 'Rüste dein erstes Item aus.',
      category: 'COLLECTION',
      icon: '⚔️',
      requirement: 1,
      rewardXp: 50,
      isSecret: false,
    },
    {
      key: 'full_set',
      name: 'Set-Sammler',
      description: 'Vervollständige ein Equipment-Set.',
      category: 'COLLECTION',
      icon: '👘',
      requirement: 1,
      rewardXp: 500,
      isSecret: false,
    },
    {
      key: 'legendary_item',
      name: 'Legendenjäger',
      description: 'Erhalte ein Legendary oder Artifact Item.',
      category: 'COLLECTION',
      icon: '💎',
      requirement: 1,
      rewardXp: 300,
      isSecret: false,
    },
    {
      key: 'all_slots',
      name: 'Voll ausgerüstet',
      description: 'Rüste alle 6 Equipment-Slots aus.',
      category: 'COLLECTION',
      icon: '🎖️',
      requirement: 6,
      rewardXp: 400,
      isSecret: false,
    },

    // ========== CATEGORY: SOCIAL (8 Achievements - für später) ==========
    {
      key: 'first_friend',
      name: 'Gesellig',
      description: 'Füge deinen ersten Freund hinzu.',
      category: 'SOCIAL',
      icon: '👋',
      requirement: 1,
      rewardXp: 100,
      isSecret: false,
    },
    {
      key: 'friends_5',
      name: 'Gemeinschaft',
      description: 'Habe 5 Freunde.',
      category: 'SOCIAL',
      icon: '👥',
      requirement: 5,
      rewardXp: 300,
      isSecret: false,
    },
    {
      key: 'challenge_won',
      name: 'Wettkämpfer',
      description: 'Gewinne deine erste Challenge.',
      category: 'SOCIAL',
      icon: '🏅',
      requirement: 1,
      rewardXp: 200,
      isSecret: false,
    },
    {
      key: 'challenges_10',
      name: 'Champion',
      description: 'Gewinne 10 Challenges.',
      category: 'SOCIAL',
      icon: '🏆',
      requirement: 10,
      rewardXp: 1000,
      isSecret: false,
    },
    {
      key: 'guild_join',
      name: 'Gemeindemitglied',
      description: 'Trete einer Gilde bei.',
      category: 'SOCIAL',
      icon: '⛪',
      requirement: 1,
      rewardXp: 150,
      isSecret: false,
    },
    {
      key: 'guild_leader',
      name: 'Gemeindeleiter',
      description: 'Gründe eine Gilde.',
      category: 'SOCIAL',
      icon: '👨‍⚖️',
      requirement: 1,
      rewardXp: 500,
      isSecret: false,
    },
    {
      key: 'top_10',
      name: 'Elite',
      description: 'Erreiche die Top 10 im Leaderboard.',
      category: 'SOCIAL',
      icon: '🥇',
      requirement: 1,
      rewardXp: 1000,
      isSecret: false,
    },
    {
      key: 'rank_1',
      name: 'Nummer Eins',
      description: 'Erreiche Platz 1 im Leaderboard.',
      category: 'SOCIAL',
      icon: '👑',
      requirement: 1,
      rewardXp: 5000,
      isSecret: true,
    },

    // ========== CATEGORY: MASTER (15 Achievements - Schwierig!) ==========
    {
      key: 'streak_7',
      name: 'Beständig',
      description: 'Erreiche einen 7-Tage Login-Streak.',
      category: 'MASTER',
      icon: '🔥',
      requirement: 7,
      rewardXp: 200,
      isSecret: false,
    },
    {
      key: 'streak_30',
      name: 'Treu',
      description: 'Erreiche einen 30-Tage Login-Streak.',
      category: 'MASTER',
      icon: '🔥🔥',
      requirement: 30,
      rewardXp: 1000,
      isSecret: false,
    },
    {
      key: 'streak_100',
      name: 'Unerschütterlich',
      description: 'Erreiche einen 100-Tage Login-Streak.',
      category: 'MASTER',
      icon: '🔥🔥🔥',
      requirement: 100,
      rewardXp: 5000,
      isSecret: false,
    },
    {
      key: 'streak_365',
      name: 'Jahres-Krieger',
      description: 'Erreiche einen 365-Tage Login-Streak!',
      category: 'MASTER',
      icon: '👑🔥👑',
      requirement: 365,
      rewardXp: 25000,
      isSecret: false,
    },
    {
      key: 'strength_1000',
      name: 'Stark',
      description: 'Erreiche 1000 Total Strength.',
      category: 'MASTER',
      icon: '💪',
      requirement: 1000,
      rewardXp: 1000,
      isSecret: false,
    },
    {
      key: 'strength_5000',
      name: 'Mächtig',
      description: 'Erreiche 5000 Total Strength.',
      category: 'MASTER',
      icon: '💪💪',
      requirement: 5000,
      rewardXp: 5000,
      isSecret: false,
    },
    {
      key: 'all_skills',
      name: 'Skill-Meister',
      description: 'Schalte alle Skills deines Rabbis frei.',
      category: 'MASTER',
      icon: '🌟',
      requirement: 10,
      rewardXp: 1000,
      isSecret: false,
    },
    {
      key: 'armor_of_god',
      name: 'Rüstung Gottes',
      description: 'Vervollständige das "Rüstung Gottes"-Set.',
      category: 'MASTER',
      icon: '🛡️✝️',
      requirement: 6,
      rewardXp: 2000,
      isSecret: false,
    },
    {
      key: 'perfect_week',
      name: 'Perfekte Woche',
      description: 'Erfülle dein tägliches Ziel 7 Tage in Folge.',
      category: 'MASTER',
      icon: '📅',
      requirement: 7,
      rewardXp: 500,
      isSecret: false,
    },
    {
      key: 'early_bird',
      name: 'Morgenlob',
      description: 'Schließe eine Lektion vor 8 Uhr morgens ab.',
      category: 'MASTER',
      icon: '🌅',
      requirement: 1,
      rewardXp: 100,
      isSecret: true,
    },
    {
      key: 'night_owl',
      name: 'Nachtwache',
      description: 'Schließe eine Lektion nach 22 Uhr ab.',
      category: 'MASTER',
      icon: '🌙',
      requirement: 1,
      rewardXp: 100,
      isSecret: true,
    },
    {
      key: 'trinity',
      name: 'Heilige Dreifaltigkeit',
      description: 'Schließe 3 Lektionen, 3 Missionen und sammle 3 Fragmente an einem Tag.',
      category: 'MASTER',
      icon: '✨',
      requirement: 1,
      rewardXp: 777,
      isSecret: true,
    },
    {
      key: 'first_day',
      name: 'Erster Tag',
      description: 'Erstelle deinen Charakter.',
      category: 'MASTER',
      icon: '🌟',
      requirement: 1,
      rewardXp: 25,
      isSecret: false,
    },
    {
      key: 'dedication',
      name: 'Hingabe',
      description: 'Verbringe 100 Stunden in der App.',
      category: 'MASTER',
      icon: '⏰',
      requirement: 100,
      rewardXp: 10000,
      isSecret: false,
    },
    {
      key: 'completionist',
      name: 'Vollständiger',
      description: 'Erreiche 100% in allen Bereichen.',
      category: 'MASTER',
      icon: '💯👑',
      requirement: 1,
      rewardXp: 50000,
      isSecret: true,
    },
  ];

  console.log(`Creating ${achievements.length} achievements...`);

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { key: achievement.key },
      update: {},
      create: achievement,
    });
  }

  console.log('✅ Achievements Seed Complete!');
  console.log(`\nBreakdown by Category:`);
  console.log(`  LEARNING: 15 achievements`);
  console.log(`  EXPLORATION: 15 achievements`);
  console.log(`  COLLECTION: 12 achievements`);
  console.log(`  SOCIAL: 8 achievements`);
  console.log(`  MASTER: 15 achievements`);
  console.log(`\nTOTAL: ${achievements.length} achievements created!`);
  console.log(`Secret Achievements: ${achievements.filter(a => a.isSecret).length}`);
}

// Allow standalone execution
if (require.main === module) {
  seedAchievements()
    .catch((error) => {
      console.error(error);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}

